platform :ios, '10.0'
use_frameworks!

target 'MYPMessageController_Example' do
  pod 'MYPMessageController', :path => '../'

  target 'MYPMessageController_Tests' do
    inherit! :search_paths

    
  end
end
